#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinHangman.Resource", IsApplication=true)]

namespace XamarinHangman
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bomb1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bomb2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bomb3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bomb4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bomb5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bomb6 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bomb7 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bomb8 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bomb9 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int explosion = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int btnDelete = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int btnEdit = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int button1 = 2131099661;
			
			// aapt resource value: 0x7f060016
			public const int button10 = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int button11 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int button12 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int button13 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int button14 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int button15 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int button16 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int button17 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int button18 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int button19 = 2131099680;
			
			// aapt resource value: 0x7f06000e
			public const int button2 = 2131099662;
			
			// aapt resource value: 0x7f060022
			public const int button20 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int button21 = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int button22 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int button23 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int button24 = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int button25 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int button26 = 2131099688;
			
			// aapt resource value: 0x7f06000f
			public const int button3 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int button4 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int button5 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int button6 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int button7 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int button8 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int button9 = 2131099669;
			
			// aapt resource value: 0x7f060033
			public const int buttonNuke = 2131099699;
			
			// aapt resource value: 0x7f06002b
			public const int imageButtonPlay = 2131099691;
			
			// aapt resource value: 0x7f06002e
			public const int imageButtonPlayers = 2131099694;
			
			// aapt resource value: 0x7f06002c
			public const int imageButtonScores = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int imageButtonSettings = 2131099693;
			
			// aapt resource value: 0x7f060009
			public const int imageViewBomb = 2131099657;
			
			// aapt resource value: 0x7f06002f
			public const int invisibleSpinner = 2131099695;
			
			// aapt resource value: 0x7f06000c
			public const int keyboardRow1 = 2131099660;
			
			// aapt resource value: 0x7f060017
			public const int keyboardRow2 = 2131099671;
			
			// aapt resource value: 0x7f060021
			public const int keyboardRow3 = 2131099681;
			
			// aapt resource value: 0x7f060002
			public const int lbldescription = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int lbltitle = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int linearLayoutGameRoot = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayoutKeyboard = 2131099659;
			
			// aapt resource value: 0x7f060029
			public const int listView1 = 2131099689;
			
			// aapt resource value: 0x7f060000
			public const int sqlite_id = 2131099648;
			
			// aapt resource value: 0x7f060032
			public const int switchNuke = 2131099698;
			
			// aapt resource value: 0x7f06002a
			public const int textViewTitle = 2131099690;
			
			// aapt resource value: 0x7f06000a
			public const int textViewWord = 2131099658;
			
			// aapt resource value: 0x7f060030
			public const int txtConfirmation = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int txtConfirmationSubtext = 2131099697;
			
			// aapt resource value: 0x7f060004
			public const int txtEditDescription = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int txtEditTitle = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddUser = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GameScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainMenu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NukeConfirmation = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Blood_Is_Pumpin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Final_Countdown = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Sandstorm = 2130968578;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
