#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinHangman.Resource", IsApplication=true)]

namespace XamarinHangman
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bomb1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bomb2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bomb3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bomb4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bomb5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bomb6 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bomb7 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bomb8 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bomb9 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int explosion = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int btnAdd = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int btnDelete = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int btnEdit = 2131034121;
			
			// aapt resource value: 0x7f050010
			public const int button1 = 2131034128;
			
			// aapt resource value: 0x7f050019
			public const int button10 = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int button11 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int button12 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int button13 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int button14 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int button15 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int button16 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int button17 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int button18 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int button19 = 2131034147;
			
			// aapt resource value: 0x7f050011
			public const int button2 = 2131034129;
			
			// aapt resource value: 0x7f050025
			public const int button20 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int button21 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int button22 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int button23 = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int button24 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int button25 = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int button26 = 2131034155;
			
			// aapt resource value: 0x7f050012
			public const int button3 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int button4 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int button5 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int button6 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int button7 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int button8 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int button9 = 2131034136;
			
			// aapt resource value: 0x7f05002e
			public const int imageButtonPlay = 2131034158;
			
			// aapt resource value: 0x7f050031
			public const int imageButtonPlayers = 2131034161;
			
			// aapt resource value: 0x7f05002f
			public const int imageButtonScores = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int imageButtonSettings = 2131034160;
			
			// aapt resource value: 0x7f05000c
			public const int imageViewBomb = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int keyboardRow1 = 2131034127;
			
			// aapt resource value: 0x7f05001a
			public const int keyboardRow2 = 2131034138;
			
			// aapt resource value: 0x7f050024
			public const int keyboardRow3 = 2131034148;
			
			// aapt resource value: 0x7f050005
			public const int lbldescription = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int lbltitle = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout1 = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int linearLayoutGameRoot = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int linearLayoutKeyboard = 2131034126;
			
			// aapt resource value: 0x7f05002c
			public const int listView1 = 2131034156;
			
			// aapt resource value: 0x7f050003
			public const int sqlite_id = 2131034115;
			
			// aapt resource value: 0x7f05002d
			public const int textViewTitle = 2131034157;
			
			// aapt resource value: 0x7f05000d
			public const int textViewWord = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int txtEditDescription = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int txtEditTitle = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int txtItemDescription = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int txtItemTitle = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GameScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainMenu = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
